### ISSUE TITLE
Add ACE-interaction for teleport menu on Spawn Point-flagpole

### ISSUE THREAD

**Issue by rundabollen** [tuntematonjr/Tun-Respawn-System#8]
**Issue.**
There is no option to enable the use of ACE-interaction for opening the teleport menu on the flagpole used in the `Spawn Point `module, whilst using the ACE-interaction menu is the default setting for the `Spawn Point`-module. This  forces mission makers to either have an inconsistent system of controls (ACE for one, addAction for another) or to only use addAction menu for all teleportation items (which in many cases is less favourable than using the ACE interaction menu).

**Suggested solution alternatives**
1.  Add setting to `Spawn Point`-module to use ACE-interaction to access teleport-menu.
2. Add CBA setting to set if all objects with Teleport menus are used with addAction or ACE interaction.

**Additional context**
I've only examined the behaviour on a SP listen server but this matches the behaviour that I've seen in MP games on Dedicated servers.

(I guess this should be labelled as a feature request but I'm not sure how to perform that action.)

**Comment by tuntematonjr** [comment]
Bit late, but flagpoles now uses ace actions. Thanks to [A] nomisum and diwakos help.
