### ISSUE TITLE
Misconfigured ace3 addaction

### ISSUE THREAD

**Issue by tanaaKa** [tuntematonjr/Tun-Respawn-System#9]
**Describe the bug**
One of the ``ace_interact_menu_fnc_addActionToClass`` calls is incorrect.

https://github.com/tuntematonjr/Tun-Respawn-System/blob/043ba90c15f597a1cbfd514a189e5194bb25b95e/addons/MSP/functions/fnc_ace_actions.sqf#L59-L61

**To Reproduce**
1. Place any unit down in the editor
2. Load into the mission
3. Script error below appears

**Expected behavior**
No script error should show

**Screenshots**
![image](https://user-images.githubusercontent.com/9407533/149679333-f6233c71-2ec8-4adc-80e2-25772ae73b1e.png)

**Desktop (please complete the following information):**
 - Arma Version 2.06.148470
 - Latest CBA
 - Latest TUN Respawn

**List of all active mods:**
 - ACE
 - CBA
 - TUN

**Comment by tanaaKa** [comment]
Upon second test, it would appear disabling the MSP option in general fixes this error. Maybe a check to see if the msp class exists in the first place?

**Comment by tuntematonjr** [comment]
Thanks, added checks for it. It will now skip invalid classnames and creates error in RPT
